networks:
  webphp_net:
  dbphp_net:

services:
  web:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html
      - ./certificate:/etc/certificate
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - webphp_net
    container_name: web
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./html/www:/var/www/html/www
    networks:
      - webphp_net
      - dbphp_net
    env_file:
      - db.env
    container_name: php
    depends_on:
      - db

  db:
    image: mariadb:10.6
    env_file:
      - db.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - maria-db:/var/lib/mysql
      - ./my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    container_name: db
    networks:
      - dbphp_net
